In [1]:
import pandas as pd

In [8]:
s1=pd.Series([10,20,30]) #8
s2=pd.Series([30,40,50])

In [10]:
add=s1+s2
print(add)

0    40
1    60
2    80
dtype: int64

In [12]:
sub=s2-s1
print(sub)

0    20
1    20
2    20
dtype: int64

In [14]:
mul=s1*s2
print(mul)

0     300
1     800
2    1500
dtype: int64

In [16]:
div=s2/s1
print(div)

0    3.000000
1    2.000000
2    1.666667
dtype: float64

In [76]:
emp=pd.read_csv('employee_data.csv') #9

In [78]:
emp[['Name','Salary']]

          Name  Salary
0   John Smith   70000
1  Alice Brown   60000
2    Bob White   80000
3   Emma Green   90000
4  Charlie Red   55000

In [82]:
emp[emp['Department']!='IT']

,EmployeeID,Name,Department,Age,Salary,JoinDate,ExperienceYears
1,102,Alice Brown,HR,28,60000,2020-03-10,3
3,104,Emma Green,Finance,40,90000,2012-05-25,11
4,105,Charlie Red,HR,25,55000,2021-06-01,2

In [145]:
emp[emp['Age']>30]

,EmployeeID,Name,Department,Age,Salary,JoinDate,ExperienceYears,Bonus,SalaryCategory
2,103,Bob White,IT,35,80000,2016-11-01,7,8000.0,High
3,104,Emma Green,Finance,40,90000,2012-05-25,11,9000.0,High

In [173]:
avg=emp.groupby('Department')['Salary'].mean()
print(avg)

Department
Finance    90000.0
HR         57500.0
IT         75000.0
Name: Salary, dtype: float64

In [171]:
emp['Department'].value_counts()

Department
IT         2
HR         2
Finance    1
Name: count, dtype: int64

In [129]:
emp['Bonus']=emp['Salary']*0.10
print(emp)

   EmployeeID         Name Department  Age  Salary    JoinDate  \
0         101   John Smith         IT   30   70000  2018-07-15
1         102  Alice Brown         HR   28   60000  2020-03-10
2         103    Bob White         IT   35   80000  2016-11-01
3         104   Emma Green    Finance   40   90000  2012-05-25
4         105  Charlie Red         HR   25   55000  2021-06-01

   ExperienceYears   Bonus
0                5  7000.0
1                3  6000.0
2                7  8000.0
3               11  9000.0
4                2  5500.0

In [117]:
emp['Department'].replace('HR','Human Resources')

0                 IT
1    Human Resources
2                 IT
3            Finance
4    Human Resources
Name: Department, dtype: object

In [157]:
emp[emp['JoinDate']==emp['JoinDate'].min()]

,EmployeeID,Name,Department,Age,Salary,JoinDate,ExperienceYears,Bonus,SalaryCategory
3,104,Emma Green,Finance,40,90000,2012-05-25,11,9000.0,High

In [137]:
emp['SalaryCategory']=['High' if x >75000 else 'Low' for x in emp['Salary']]
print(emp)

   EmployeeID         Name Department  Age  Salary    JoinDate  \
0         101   John Smith         IT   30   70000  2018-07-15
1         102  Alice Brown         HR   28   60000  2020-03-10
2         103    Bob White         IT   35   80000  2016-11-01
3         104   Emma Green    Finance   40   90000  2012-05-25
4         105  Charlie Red         HR   25   55000  2021-06-01

   ExperienceYears   Bonus SalaryCategory
0                5  7000.0            Low
1                3  6000.0            Low
2                7  8000.0           High
3               11  9000.0           High
4                2  5500.0            Low

In [161]:
duplicate=emp.drop_duplicates(subset='EmployeeID')
print(emp)

   EmployeeID         Name Department  Age  Salary    JoinDate  \
0         101   John Smith         IT   30   70000  2018-07-15
1         102  Alice Brown         HR   28   60000  2020-03-10
2         103    Bob White         IT   35   80000  2016-11-01
3         104   Emma Green    Finance   40   90000  2012-05-25
4         105  Charlie Red         HR   25   55000  2021-06-01

   ExperienceYears   Bonus SalaryCategory
0                5  7000.0            Low
1                3  6000.0            Low
2                7  8000.0           High
3               11  9000.0           High
4                2  5500.0            Low

In [104]:
emp['Age'].median()

30.0